### PR TITLE
ol3pickr - UI for a component-picker for a customized ol3 JS lib

### PR DESCRIPTION
**Pull request by eshon**
Live example:

http://eshon.github.io/openlayers.github.io/ol3pickr/ol3pickr.html

Questions:
1. Has description been added to the symbols in a new json output?
2. On expanding ol.tilegrid:

TileGrid appears twice, once as its own class, and second time as the root of a set of functions. Is this correct or should it only appear once (can you include the class without all of its methods?)?
1. What format of json should be submitted by the form to the server?
2. Should there be categories for Core, Touch, etc.?
3. Should I make a PR of the live page on the gh-pages branch as well?

### CODE REVIEW

**Comment by ahocevar** [comment]
Thanks @eshon for working on this. Here are a few answers:

> Has description been added to the symbols in a new json output?

Yes. Here is a [`build/info.json`](https://gist.github.com/ahocevar/3ce4dfa4a9c5156134ec/raw/info.json) file from current master.

> TileGrid appears twice, once as its own class, and second time as the root of a set of functions. Is this correct or should it only appear once (can you include the class without all of its methods?)?

There seems to be a problem. It should only appear once. You can see the same problem with all classes from the `ol.tilegrid` namespace (like XYZ, WMTS).

> What format of json should be submitted by the form to the server?

We have to flesh that out. It may also be the case that we have to move this pull request to a different repository. I've added this as [sprint task](https://github.com/openlayers/ol3/wiki/OpenLayers-3-Austria-Code-Sprint-Spring-2015#ideas-from-andreas) for Schladming. I'll keep you posted.

> Should there be categories for Core, Touch, etc.?

I don't think this will be necessary. But sorting the categories alphabetically might help.

> Should I make a PR of the live page on the gh-pages branch as well?

Since we don't know yet where and how this is going to be hosted, it is perfectly fine to have it available the way it is for now.

**Comment by ohmu808** [comment]
Classes appearing twice should be fixed but there are a few bugs with it that I need to address e.g. ol.tilegrid.WMTS.createFromCapabilitiesMatrixSet not appearing in the right subgroup.

**Comment by jipexu** [comment]
is this request still valid (7yr) ? If not it could be closed?

**Comment by tschaub** [comment]
I think it is probably safe to close.

**Pull request closed without merging**
