### PR TITLE
Master

### PR DESCRIPTION
**Pull request by sangita23**
[Mastering OpenLayers 3
](url
image
)
[OpenLayers 3: Beginner's Guide](url
image
)
Please add the above books to http://openlayers.org/

### CODE REVIEW

**Comment by ahocevar** [comment]
What's in for the OpenLayers project if we add these?

Closing this pull request, because it was created in a way that makes it impossible to review the suggested changes.

**Comment by marcjansen** [comment]
Plus one for closing, @ahocevar. But I still find it is a useful thing to link to more (good) resources. Probably not from the startpage but from http://openlayers.org/en/v3.14.0/doc/

**Comment by sangita23** [comment]
Hi,
Having books on OpenLayers could be a great resource to anyone seeking help on the subject. It gives an insight on the advanced functionalities used in OpenLayers 3.

**Comment by ahocevar** [comment]
@sangita23 If you are a representative of Packt Publishing, please get in touch with the [Project Steering Committee](https://lists.osgeo.org/mailman/listinfo/openlayers-psc) to discuss advertising of Packt Publishing books on the OpenLayers website.

**Pull request closed without merging**
