### PR TITLE
update js and css dependancies

### PR DESCRIPTION
**Pull request by jipexu**
?? why jquery is charged 2 time ??
 ??<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>?? <= no need ?

### CODE REVIEW

**Comment by ahocevar** [comment]
> ?? why jquery is charged 2 time ??
> ??<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>?? <= no need ?

I don't think this was intentional. Should be safe to remove.

**Comment by jipexu** [comment]
@ahocevar  thanks 
may i turn temporary to ready for review ( as this i will can use deploy to see what  i do :-)  ... and after i turn back to draft ?..

**Comment by ahocevar** [comment]
@jipexu Unfortunately, this change breaks the menu bar:

Untitled

If you want to continue on this branch and test locally, just run

    npm install
    npm start

and navigate to http://localhost:8080/

**Comment by jipexu** [comment]
yes i waiting some probleme for this... ok i re try to test on my machine

**Comment by ahocevar** [comment]
Will this be replaced by #107, or are you still working on it here?

**Comment by jipexu** [comment]
yes replace with 107

**Pull request closed without merging**
