### PR TITLE
Add link to OL3 workshop to homepage

### PR DESCRIPTION
**Pull request by eshon**
This workshop is hard to find!

### CODE REVIEW

**Comment by marcjansen** [comment]
+1

And is everything in the workshop working with master?

**Comment by tschaub** [comment]
> And is everything in the workshop working with master?

Nope.  Specifically, `ol.source.GeoJSON`.  Maybe more.

**Comment by tschaub** [comment]
At the sprint we discussed moving all documentation related resources to the documentation page.

**Comment by eshon** [comment]
One of our devs didn't realize 'Docs' was different from 'API'.  Maybe 'Resources' would be a better term, or 'Getting Started' or 'Learn'.

**Comment by tschaub** [comment]
> One of our devs didn't realize 'Docs' was different from 'API'. Maybe 'Resources' would be a better term, or 'Getting Started' or 'Learn'.

See also 19a416f330edbc01b06db6a6eda12b3d70796f98.  Design by committee FTW!

**Comment by eshon** [comment]
Nice!

**Comment by bartvde** [comment]
@eshon so actually what was changed recently is opposite from what you proposed? You say Learn is better than Docs right? It's what we had before.

**Pull request closed without merging**
